//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroDeCorreos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAdjuntosCorreoPruebas
    {
        public long id { get; set; }
        public long idCorreoElectronico { get; set; }
        public string NombreArchivo { get; set; }
        public string RutaArchivo { get; set; }
        public string idTemporal { get; set; }
        public bool TipoMime { get; set; }
    
        public virtual tblCorreosElectronicosPruebas tblCorreosElectronicosPruebas { get; set; }
    }
}
