//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CentroDeCorreos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuarioSynergiaRelCatFranquicia
    {
        public long id { get; set; }
        public long idUsuarioSynergia { get; set; }
        public long idFranquicia { get; set; }
        public short Orden { get; set; }
    
        public virtual tblUsuarioSynergia tblUsuarioSynergia { get; set; }
    }
}
